# Copyright (c) 2026 Erick Bourgeois, banlieue
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: banlieue-controller
  namespace: banlieue-system
  labels:
    app.kubernetes.io/name: banlieue
    app.kubernetes.io/component: controller
