// Copyright (c) 2026 Erick Bourgeois, banlieue
// SPDX-License-Identifier: Apache-2.0
//! Render banlieue CRDs as a single Markdown API-reference page.
//!
//! Gated behind the `crdgen` feature and used by the `crddoc` binary. The
//! generated page (`docs/src/reference/api.md`) lets users browse the full CRD
//! schema — every field, type, and description — in the rendered docs site.
//!
//! Source of truth is the Rust types: descriptions come straight from the
//! rustdoc comments via schemars / kube-derive, with the same
//! [`crate::crdgen_support::prepared`] root-description promotion applied. The
//! file is generated, never hand-edited — regenerate with `make api-docs`
//! (also run as part of `make crds`).

use std::collections::BTreeSet;

use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::{
    CustomResourceDefinition, JSONSchemaProps, JSONSchemaPropsOrArray, JSONSchemaPropsOrBool,
};

/// Heading levels. `##` per CRD, `###` per top-level sub-resource (spec /
/// status), then one deeper per level of nesting.
const CRD_HEADING_LEVEL: usize = 2;
const SUBRESOURCE_HEADING_LEVEL: usize = 3;

/// Top-level object properties that are standard Kubernetes plumbing and not
/// worth documenting per-CRD.
const SKIPPED_ROOT_PROPERTIES: [&str; 3] = ["apiVersion", "kind", "metadata"];

/// Render the complete API-reference Markdown page for every supplied CRD.
pub fn render_reference(crds: &[CustomResourceDefinition]) -> String {
    let mut out = String::new();
    push_preamble(&mut out, crds);
    for crd in crds {
        render_crd(&mut out, crd);
    }
    out
}

/// Page title, generated-file warning, and a grouped index of every CRD.
fn push_preamble(out: &mut String, crds: &[CustomResourceDefinition]) {
    out.push_str("# API Reference\n\n");
    out.push_str(
        "<!-- Generated by `cargo run -p banlieue-api --bin crddoc` (make api-docs). \
         Do not edit by hand — edit the Rust types in crates/banlieue-api. -->\n\n",
    );
    out.push_str(
        "Every banlieue Custom Resource Definition, generated from the Rust \
         types that are the schema's source of truth. Field descriptions are the \
         rustdoc comments on those types.\n\n",
    );

    // Index grouped by API group.
    let mut groups: BTreeSet<&str> = BTreeSet::new();
    for crd in crds {
        groups.insert(crd.spec.group.as_str());
    }
    for group in &groups {
        out.push_str(&format!("**`{group}`**\n\n"));
        for crd in crds.iter().filter(|c| &c.spec.group == group) {
            let kind = &crd.spec.names.kind;
            out.push_str(&format!("- [{kind}](#{})\n", heading_anchor(kind)));
        }
        out.push('\n');
    }
    out.push_str("---\n\n");
}

/// Render one CRD: heading, metadata line, root description, printer columns,
/// then the `spec` and `status` schemas.
fn render_crd(out: &mut String, crd: &CustomResourceDefinition) {
    let kind = &crd.spec.names.kind;
    out.push_str(&format!("{} {kind}\n\n", "#".repeat(CRD_HEADING_LEVEL)));

    // Pick the storage version, falling back to the first served version.
    let Some(version) = crd
        .spec
        .versions
        .iter()
        .find(|v| v.storage)
        .or_else(|| crd.spec.versions.first())
    else {
        return;
    };

    let short_names = crd
        .spec
        .names
        .short_names
        .as_deref()
        .unwrap_or_default()
        .iter()
        .map(|s| format!("`{s}`"))
        .collect::<Vec<_>>()
        .join(", ");
    let short_names = if short_names.is_empty() {
        "—".to_string()
    } else {
        short_names
    };
    out.push_str(&format!(
        "**API:** `{}/{}` · **Kind:** `{kind}` · **Scope:** {} · **Short names:** {short_names}\n\n",
        crd.spec.group, version.name, crd.spec.scope,
    ));

    let Some(root) = version
        .schema
        .as_ref()
        .and_then(|s| s.open_api_v3_schema.as_ref())
    else {
        return;
    };

    if let Some(description) = root.description.as_deref() {
        out.push_str(&format!("{}\n\n", prose(description)));
    }

    render_printer_columns(out, version);

    // Document spec and status (skip apiVersion / kind / metadata).
    let Some(properties) = root.properties.as_ref() else {
        return;
    };
    for name in ["spec", "status"] {
        if SKIPPED_ROOT_PROPERTIES.contains(&name) {
            continue;
        }
        if let Some(schema) = properties.get(name) {
            // `prepared()` promotes the spec description to the CRD root, so it
            // is already shown above — don't repeat it in the `.spec` section.
            let description = match schema.description.as_deref() {
                Some(d) if Some(d) == root.description.as_deref() => None,
                other => other,
            };
            emit_object(
                out,
                &format!(".{name}"),
                description,
                schema,
                SUBRESOURCE_HEADING_LEVEL,
            );
        }
    }

    out.push_str("---\n\n");
}

/// Render the `kubectl get` additional printer columns, if any.
fn render_printer_columns(
    out: &mut String,
    version: &k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinitionVersion,
) {
    let Some(columns) = version.additional_printer_columns.as_ref() else {
        return;
    };
    if columns.is_empty() {
        return;
    }
    out.push_str("**Printer columns** (`kubectl get`):\n\n");
    out.push_str("| Name | Type | JSON path | Priority |\n| --- | --- | --- | --- |\n");
    for col in columns {
        out.push_str(&format!(
            "| {} | {} | `{}` | {} |\n",
            col.name,
            col.type_,
            col.json_path,
            col.priority.unwrap_or(0),
        ));
    }
    out.push('\n');
}

/// Emit an object schema as a heading + a field table, then recurse into any
/// nested object / array-of-object / map-of-object properties.
fn emit_object(
    out: &mut String,
    path: &str,
    description: Option<&str>,
    obj: &JSONSchemaProps,
    level: usize,
) {
    out.push_str(&format!("{} `{path}`\n\n", "#".repeat(level)));
    if let Some(desc) = description {
        out.push_str(&format!("{}\n\n", prose(desc)));
    }

    let Some(properties) = obj.properties.as_ref() else {
        return;
    };
    let required: BTreeSet<&str> = obj
        .required
        .as_deref()
        .unwrap_or_default()
        .iter()
        .map(String::as_str)
        .collect();

    out.push_str("| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n");
    for (name, prop) in properties {
        let required_mark = if required.contains(name.as_str()) {
            "Yes"
        } else {
            ""
        };
        out.push_str(&format!(
            "| `{name}` | {} | {required_mark} | {} |\n",
            type_label(prop),
            cell_description(prop),
        ));
    }
    out.push('\n');

    // Recurse into nested objects so their full descriptions render as prose.
    for (name, prop) in properties {
        if let Some((inner, suffix)) = resolve_object(prop) {
            emit_object(
                out,
                &format!("{path}.{name}{suffix}"),
                prop.description.as_deref(),
                inner,
                level + 1,
            );
        }
    }
}

/// If `schema` (or its array items / map values) is an object with its own
/// properties, return that object schema plus a path suffix marking how it is
/// nested (`""` direct, `"[]"` array element, `"{}"` map value).
fn resolve_object(schema: &JSONSchemaProps) -> Option<(&JSONSchemaProps, &'static str)> {
    if schema.properties.is_some() {
        return Some((schema, ""));
    }
    if let Some(JSONSchemaPropsOrArray::Schema(item)) = schema.items.as_ref()
        && item.properties.is_some()
    {
        return Some((item, "[]"));
    }
    if let Some(JSONSchemaPropsOrBool::Schema(value)) = schema.additional_properties.as_ref()
        && value.properties.is_some()
    {
        return Some((value, "{}"));
    }
    None
}

/// Human-readable type label for a schema property.
fn type_label(schema: &JSONSchemaProps) -> String {
    // Array: `<item>[]`.
    if schema.type_.as_deref() == Some("array") {
        if let Some(JSONSchemaPropsOrArray::Schema(item)) = schema.items.as_ref() {
            return format!("{}[]", type_label(item));
        }
        return "array".to_string();
    }

    // Object: either a map (additionalProperties) or a nested object.
    if schema.type_.as_deref() == Some("object") {
        return match schema.additional_properties.as_ref() {
            Some(JSONSchemaPropsOrBool::Schema(value)) => {
                format!("map[string]{}", type_label(value))
            }
            _ => "object".to_string(),
        };
    }

    // Enum scalars are reported by their base type; allowed values go in the
    // description cell.
    schema.type_.clone().unwrap_or_else(|| "object".to_string())
}

/// One-line description cell: the first paragraph of the rustdoc comment, with
/// enum values appended. Newlines are collapsed and table-breaking characters
/// escaped so the Markdown table stays intact; full multi-line descriptions
/// still render as prose in each nested object's own section.
fn cell_description(schema: &JSONSchemaProps) -> String {
    let mut text = schema
        .description
        .as_deref()
        .map(first_paragraph)
        .unwrap_or_default();

    if let Some(values) = enum_values(schema) {
        if !text.is_empty() && !text.ends_with('.') {
            text.push('.');
        }
        let joined = values
            .iter()
            .map(|v| format!("`{v}`"))
            .collect::<Vec<_>>()
            .join(", ");
        text.push_str(&format!(" Allowed: {joined}."));
    }

    escape_cell(text.trim())
}

/// Prepare a multi-line rustdoc description for rendering as page prose.
///
/// Demotes Markdown ATX headings (`# Why`, `## How`) authored inside doc
/// comments to bold lines, so they don't inject competing top-level headings
/// into the reference page (which would pollute the page's table of contents).
/// Other lines pass through unchanged.
fn prose(description: &str) -> String {
    description
        .trim()
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            if trimmed.starts_with('#') {
                let title = trimmed.trim_start_matches('#').trim();
                format!("**{title}**")
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// First paragraph of a (possibly multi-line) description, whitespace-collapsed.
fn first_paragraph(description: &str) -> String {
    let paragraph = description.split("\n\n").next().unwrap_or(description);
    paragraph.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Allowed values for an enum schema, as strings.
fn enum_values(schema: &JSONSchemaProps) -> Option<Vec<String>> {
    let raw = schema.enum_.as_ref()?;
    let values: Vec<String> = raw
        .iter()
        .map(|json| match &json.0 {
            serde_json::Value::String(s) => s.clone(),
            other => other.to_string(),
        })
        .collect();
    if values.is_empty() {
        None
    } else {
        Some(values)
    }
}

/// Escape characters that would break a Markdown table cell.
fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

/// GitHub/MkDocs-style heading anchor: lowercase, spaces to hyphens.
fn heading_anchor(heading: &str) -> String {
    heading.to_lowercase().replace(' ', "-")
}

#[cfg(test)]
#[path = "crddoc_tests.rs"]
mod crddoc_tests;
