# Copyright (c) 2026 Erick Bourgeois, banlieue
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: banlieue-operator
  labels:
    app.kubernetes.io/name: banlieue
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: banlieue-operator
subjects:
  - kind: ServiceAccount
    name: banlieue-operator
    namespace: banlieue-system
